[project]
name = "kshs-management-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.33.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
    "supabase>=2.15.2",
]
